sudo: required

language: generic

services:
  - docker

before_install:
  - docker build -t sunsplash/docker-demo-frontend -f Dockerfile.dev .

script:
  - docker run sunsplash/docker-demo-frontend npm run ci:test